### ISSUE TITLE
step 5 doesn't work with firebase version 3.10.0

### ISSUE THREAD

**Issue by DeeVine** [firebase/friendlychat-web#241]
I kept getting the error "Unable to authorize access to project" after making sure I was logged in and  selecting the project with firebase --add.

Once I reverted to an older version of firebase 3.9.0 everything worked as expected.

**Comment by nvdhunter** [comment]
I Found the answer https://stackoverflow.com/a/45333192/8556970

**Comment by abrahamjsb** [comment]
Same issue around here.. When I runned *firebase serve* returned me: 
`Error: Unable to authorize access to project project-alias`

**Comment by WolfVic** [comment]
I have the same issue after deploy the project...

**Comment by abrahamjsb** [comment]
I solved with **firebase init** without overwrite the init files and done!

**Comment by animeshk874** [comment]
As @nvdhunter already mentioned, you can try
`firebase serve --project projectID`

To get the projectID, type
`firebase list`

**Comment by shock-wave007** [comment]
i still cant get it right. 
"Welcome

Firebase Hosting Setup Complete

You're seeing this because you've successfully setup Firebase Hosting. Now it's time to go build something extraordinary!"

please tell what to overwrite and other options, its like i have tryd for 10s of time but failed.

**Comment by jwilleke** [comment]
> firebase serve --project projectid

Worked for me but still people should not need to go here to find this workaround.
This is a bug that should be addressed in the Codelab.

**Comment by shock-wave007** [comment]
simplest way to get this, type the following command in terminal without quotes
prerequisite
1."npm -g install firebase-tools"
2."firebase --version"Make sure the Firebase version is above 3.3.0
steps
1. creat a folder
2.open terminal on new folder address
3."firebase login" login firebase(skip if already login)
4."firebase use --add"
5."firebase init" follow the steps yes in all and when ask for public folder type "./" hit enter without quotes

wait to install and download files

6. copy all the content of folder "web-start" or "web" or "cloud-functions-start" or "cloud-functions" anyone of the folder and paste it in that new created folder in step one and overwrite all the files.

7. "firebase serve" or u can deploy "firebase deploy"

**Comment by jwilleke** [comment]
Still a workaround to a bug. (ie codelab is broken)
Expecting someone, just learning to even find this page is asking a lot. Many people would just quit and give up on firebase.

**Comment by nicolasgarnier** [comment]
@mbleigh looks like lots of people are facing an auth issue with the latest firebase tools. i.e. getting an auth error when doing `firebase serve` just after doing `firebase login` and `firebase add`. This may be an issue with `firebase-tools` rather than the codelab (since it's working fine with v 3.3.0 of the CLI).

(please also look at the last comment in #74 which has the step-by-step repro)

All facing this issue: Were you users of firebase tools before (i.e. did you already have the firebase CLI authorized?). Coud you try doing:

`firebase logout` followed by `firebase login` (logout then login again...).

I need to try to repro too but I'm currently OOO...

**Comment by nicolasgarnier** [comment]
Or please try to run: `firebase login --reauth` and let us know if this works for you please

**Comment by jwilleke** [comment]
jmac:functions jim$ firebase deploy --only functions

Error: Unable to authorize access to project staging
jmac:functions jim$ firebase logout
✔  Logged out from jim@willeke.com
jmac:functions jim$ firebase login
? Allow Firebase to collect anonymous CLI usage information? Yes

Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?.....

Waiting for authentication...

✔  Success! Logged in as jim@willeke.com
jmac:functions jim$ firebase deploy --only functions

Error: Unable to authorize access to project staging

Same for firebase login --reauth.

**Comment by DeeVine** [comment]
@nicolasgarnier 

firebase login --reauth doesn't solve the problem
firebase serve --project projectID mentioned by @WolfVic is a working solution

**Comment by nicolasgarnier** [comment]
Thanks all!

I can definitely repro the issue with the Firebase CLI v 3.10:

![image](https://user-images.githubusercontent.com/3766663/30233413-618404f0-94ed-11e7-8422-a712a630f337.png)

**Comment by nicolasgarnier** [comment]
@mbleigh it looks like the bug is that the Firebase CLI is trying to use the alias used in `firebase use` as the ID of the project to serve. See abode: it's trying to serve a project called `staging` instead of `friendlychat-1234`.

Actually if you use a real project ID as the alias it works:

![image](https://user-images.githubusercontent.com/3766663/30233558-30956c52-94ee-11e7-87a8-db6c84202bb7.png)

**Comment by nicolasgarnier** [comment]
@mbleigh is working on fixing `firebase-tools`. I'm guessing a new build will be out shortly (probably 3.10.1) with the fix.

**Comment by nicolasgarnier** [comment]
It's out!

https://www.npmjs.com/package/firebase-tools

Please run `npm install -g firebase-tools` to update to the latest version of the Firebase CLI and try the codelab again. This should work:

![image](https://user-images.githubusercontent.com/3766663/30234535-eb902edc-94f5-11e7-9766-4df51166778f.png)

Thanks all for reporting this!
